### ISSUE TITLE
FileWatcher Prod. Bug analysis & fix

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-file-conversion#13]
Refer #157

1. Try to replicate folder structure on TEST, by our own and reproduce the issue.,
2. if step 1 fails, request for IDIR(developer) access to \\sfp. file share(prod) . so that it is easy debug.
3. Remove watching archive or CRF done folders - TBD
4. Check permission on CFR folder with IMB.

**Comment by abin-aot** [comment]
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/157

**Comment by abin-aot** [comment]
Refer Files under : \\sfp.idir.bcgov\S177\S77104\HTH-MHA\Call For Records\HTH-2021-10680-Excel\PHO-Excels , Conversion

**Comment by arielleandrews** [comment]
Email sent Jul 15 canvassing Flex team for any known issues with file conversion to date, will log any responses here

FYI @abin-aot @divyav-aot @m-prodan

**Comment by arielleandrews** [comment]
Folder "FNR-2020-01183 Excels" - Excel files not converting at all
Folder containing "MOE-2021-11203" - 600+ Excel files, approx. 80 files Failed
Folder containing "MOE-2021-12443" - iCalendars converted but not usable, one Failed

**Comment by m-prodan** [comment]
Folder containing (MSD\Call for Records\P-MSD-2021-12427 - Marion) - advised today only one of the two excel files converted successfully. Analyst also asked if possible to have these in landscape view with grid lines showing.

**Comment by m-prodan** [comment]
Another one from MSD: MSD\Call for Records\P-MSD-2021-12330 Leala\

In ELMSD folder - none of the 2 excel files picked up for converting 
GA Folder - had excel files produced

No log folder created. 

One of the excel files we looked at in the ELMSD folder was a very simple excel file, just text based with small number of columns and minimal data - unclear why it wasn't picked up.

**Comment by arielleandrews** [comment]
Additional issues reported:
"Z:\FNR\In_Coming\FNR-2021-12728" - There is errors occurring and cant convert to pdf 
"Z:\ARR\In_Coming\IRR-2021-12890 - Jazmine Anderson Records" - error messages reported in Log files

**Comment by m-prodan** [comment]
PSA-2021-12112 - flagged as having issues:

the analyst (Dave McCallum) says:
•	that they don’t remember seeing an Output folder but “I didn’t delete it”
•	The product was too small to read and didn’t fit so he didn’t use them. He redid the conversion of the three excell spreadsheets manually (and deleted the FileWatch products)
•	As he remembers it…he says found the FileWatch product in the CHIPS folder.
because I didn’t see the original records I can’t verify that there was no Output folder.

- So apparently something converted, but not in an output folder? This group has flagged several folders with (File Watch Case) where there were issues converting. 

Also flagged, PSA-2021-12280

The analyst (Josh Robinson) says:
•	There was no Output folder and he didn’t delete one.
•	Other than the Log folder There was no FileWatch product anywhere (no “converted to pdf” documents)
•	The native format Excel were in the CHIPS folder and the analyst manually converted them (as seen in the snippet).

**Comment by abin-aot** [comment]
@lmullane @m-prodan @arielleandrews 

**_Excel Conversion Issues, Root Cause and fixes_**
---------------------------------------------------------------------
A good majority of the issues with Excel file conversion has been resolved. Main cause of failures with Excel conversion  is related with the Formulas & its cross reference with multiple sheets, related errors with in it. This has been handled with in code to convert the spreadsheets, making that cell with "error" text.  Also, there were errors with worksheet with special characters like " > , < " , which in turn while converting to pdf in output folder causing the conversion error. This has handled to eliminate those characters in file names. These are RCA comments on the Excel files. 

Couple of reporting was related to increasing Zoom level of converted PDFs or use Landscape - As mentioned earlier, we are having a generic approach to handle all excel sheets and its been understood that most of excel files fall into portrait. But when I checked, we can see the content on pdf by zooming into up to 400% and Intella supports it by 800%- confirmed during initial development time.  @arielleandrews, Please confirm this. But nothing is stopping us to implement a dynamic logic to switch between Landscape and Portrait. 

**HTH-2021-10680-Excel - PHO Excels-original** - Fixed issue, Root cause : Worksheet has special characters, which in turns while creating pdf file had issues
**IRR-2021-12890 - Jazmine Anderson Records** - Fixed issue, Root cause : Formula issue with File Conversion. Certain formula's cant be handled while converted to PDF 
**P-MSD-2021-12330 Leala** - Fixed: Issues with Formula on excel
**PSA-2021-12112** - Checked, working fine and converting on local, need to zoom. Possibly a formula, special character issue on worksheet
**PSA-2021-12280** - Checked, working fine and converting on local, need to zoom. Possibly a formula, special character issue on worksheet
**MOE-2021-11203 - 600+ excel location** - Few excel files(~89) had errors on formula , which blocked the conversion. Fixed that.
**FNR-2021-12729** - Unable to reproduce, working fine. Possibly a Network issue
**FNR-2021-12728** -  Unable to reproduce, working fine. Possibly a Network issue
**P-MSD-2021-12427 - Marion** - non reproducible
**FNR-2020-01183 Excels** - non-reproduceble

**_ICalender Conversion_**
--------------------------------------------
Regarding ICalenders conversion, the files that are location inside the below CFR folders are NOT actually the .ics files. It seems somebody my mistake saved .msg files as .ics file. because when I tried to open those ics files, its giving an error. which made me to remove the .ics extension and open it again . That made things to open as a MSG file in Outlook. it worked!. So we might to communicate , how to create .ICS file from outlook calender. They might need to go to outlook calendar --> select the event -- Go to File Menu(top left) --> Save as type, ICS.

**MAG-2021-12512** - Checked - Icalender, its MSG files basically, corrupted .ics files
**MOE-2021-12443**  - Checked - Icalender, its MSG files basically, corrupted .ics files


**_Things to do for better functionality_**
------------------------------------------

1. Archive CRF Folders which is not in use - ASAP, avoid duplicate CFR for FileConversion, if required create sub-folders. With this fix, I have incorporated "CRF Archive" folder to skip file watching, which can utilized for this. 
2. After Creating CRF Folder, please wait for 30 seconds before moving files to it. Means, please 
don't create CFR folder locally, with files and move it all together
3. Please avoid rearranging folders and files once moved into CFR, this will cause issue with FileWatching in general.
4. Save Icalender in proper way, Go to Calender, select the event and from the "File" menu(top-left), Save as default(.ICS)


**_Unknowns, suggestions to handle unknown etc_**
--------------------------------------------------------------

- Considering the point that we don't have a proper LAN on Test environment, the ways to handles permissions, network issues is challenging. so in future if the issues with network/un-reproducible are more, then we might need to think about different plans for handling FileConversions. Like, avoiding current LAN or providing interactive web app to do File Conversion for IAO or sometimes , separate ministries on different FileConversion Service to understand which has these issues more.
-
