### ISSUE TITLE
Session timeout page should be homepage

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-file-conversion#20]
**Describe the bug in current situation**
When a session timeouts the user is routed to an XML page not the homepage.

**Link bug to the User Story**

**Impact of this bug**
Impacts all users. Must be fixed before release to users.

**Chance of Occurring (high/medium/low/very low)**
High. Every timeout.
**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Login
2. Let session expire and leave browser window open
3. Return to browser window
4. See XML page (see attached image)

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN a user's session has expired
WHEN the user clicks on the open browser window
THEN the user should see the homepage:
https://test-foirequest.apps.silver.devops.gov.bc.ca/
AND the user will need to login

**Screenshots/ Visual Reference/ Source**
![Screen Shot 2021-07-26 at 10.05.27 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/2eb58761-661d-4ae3-86aa-8cef8f409ed0)

**Comment by m-prodan** [comment]
Behaviour has been corrected.
