### ISSUE TITLE
Select Start Date after End Date

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-file-conversion#21]
**Describe the bug in current situation**
This bug was not part of the stories acceptance criteria.

When editing the date range for a request, the user can select a start date after the end date.

**Link bug to the User Story**
#77
**Impact of this bug**
Impacts all users, but user unlikely to select 'Start Date' before 'End Date'. They can also correct the error.

Impact is low.

**Chance of Occurring (high/medium/low/very low)**
Low - see above

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request view (e.g., https://test-foirequest.apps.silver.devops.gov.bc.ca/foi/reviewrequest/32 )
2. Click on calendar icon for 'Start Date'
3. Click 'Start Date' after 'End Date'

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN has the 'Start Date' calendar open
WHEN the user clicks on any 'Start Date' after the selected 'End Date' (can choose the same date)
THEN the date will be greyed out and cannot be selected

**Screenshots/ Visual Reference/ Source**
![Screen Shot 2021-07-26 at 10.19.59 AM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/2cb986d9-d0a9-417b-b521-4b6e29f85dd4)

**Comment by abin-aot** [comment]
@lmullane , myself and @divyav-aot was looking at this bug and it seems like startdate can be changed to a date after enddate, **but soon after enddate will get reset to startdate** . 

Scenario : StartDate set as '1-June-2020' and EndDate as '30-June-2020'. Then, when IAO analyst decides to change the start date to '1-August-2020' based on their conversations, and we should allow that and soon after that change 'EndDate' will be become '1-August-2020'.

Note : Startdate and ENddate will not go beyond current date- which is done!.

**Comment by lmullane** [comment]
Good with that solution.
