### ISSUE TITLE
CFR Folder Archival Policy Set up

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-file-conversion#27]
Title of ticket: 

#### Description
Just thought to highlight the issue I raised earlier. For the better performance of _File Watcher,_ the count of active CFR folders is important. or in other words, _File Watcher_ will stop working if there are very high amount of folders to be watched. This issue happened on the first day release to Prod. of _file watcher_. So, we put a start date on File Watcher to monitor only the Folders created after that date. Its June 21, 2021 as of now. But as days progress, CFR folder count get increased and we will fall the issue soon. As part of this problem, we discussed and I suggested to move/archive CFR folders to a location once the CFR stage is completed. THis is will help File Watcher to monitor only the active CFR folders.  We are waiting on the decision from IAO Team, whether they are good with moving old folders to "CFR Archive" folder to not.
#### Dependencies
Are there any dependencies? - IAO Team Decision

#### DOD
- [x] Decision on Archival of CFR Folder
- [x] Process to Archive
- [x] Does the process decided aligned with Code/FileWatcher Production Deployment
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
Decision - Will archive monthly
