### ISSUE TITLE
Syncfusion Production License configuration issue

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-file-conversion#30]
**Describe the bug in current situation**
While opening the PDF outputs of the problematic file types , the Syncfusion watermark is getting displayed on the PDF outputs and/or subsequent PDF output files are marked as blank. The root cause of this issue was related with Syncfusion License Key configured on Prod. 

**Link bug to the User Story**

**Impact of this bug**
This bug has a Production wide issue with all conversion starting from September 1st. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to \\Sfp.idir.bcgov\S177\S77104\ARR\In_Coming\IRR-2021-12586 - Sasha Andres CFR - Excel\output\Excel Documents
2. Open PDF outputs and we can see watermark on the TOP

**Actual/ observed behaviour/ results**

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/9e47efc2-217b-4a14-9e64-a01105b4a6da)

**Expected behaviour**
Water mark should not have displayed

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
Issue fixed by configuring new License Key. No watermarks on Prod. now.  Refer SMOKETEST folder on \\Sfp.idir.bcgov\S177\S77104\ARR\In_Coming\IRR-SMOKETEST-AJA\output\Excel Documents

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/f4adaee5-89a0-46a0-80ec-01a4d7c15000)

**Comment by arielleandrews** [comment]
@abin-aot I did a test and confirmed this issue is resolved. I also spoke with the Flex Team and the workaround put in place for them for any previous files is sufficient. This can be closed.
