### ISSUE TITLE
FileWatcher Errors

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-file-conversion#31]
**Describe the bug in current situation**
IAO Flex Team analysts have reported a number of errors with FileWatcher conversions.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

- MAG-2021-12992 and FIN-2021-12993 (same records): \\Sfp.idir.bcgov\S177\S77104\AGPSSG\Call For Records\MAG-2021-12992 - Sasha Andres 
Error when converting records, text from one column was moved to the next. Exception noted in Log file
- LBR-2021-12468: \\Sfp.idir.bcgov\S177\S77104\EconSector\Call For Records\LBR-2021-12468 - Judy Law - Deduplication Required
Appears the FileWatcher exported some icons from emails attachments as JPG and PNG files
- AGR-2021-13402: \\Sfp.idir.bcgov\S177\S77104\AGR\In_Coming\13402
Possible edge case Excel file - some sheets converted but not others
- MOE-2021-13742: \\Sfp.idir.bcgov\S177\S77104\MOE\In_Coming\MOE-2021-13742 - Jazmine Anderson - Records
Output pdf gives the below error message when opened. Log file does not note any errors.
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/10a02180-5752-41f1-9ca5-3dce7889694f)

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by arielleandrews** [comment]
@abin-aot and @divyav-aot ticket created to log some FileWatcher conversion errors reported by the Flex Team.

FYI @lmullane

**Comment by lmullane** [comment]
Thanks for capturing these, @arielleandrews
